server:
  port: 8081

spring:
  application:
    name: so-movie
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.234.1:8848
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/picture?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
      username: root
      password: 123456
  rabbitmq:
    host: 94.191.125.116
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 100

  mail:
    host: smtp.163.com
    username: 15671640540@163.com
    password: LLyy123456789
    from: 15671640540@163.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true