server:
  port: 8081

spring:
  application:
    name: so-movie
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.234.1:8848
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/picture?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
      username: root
      password: 123456